# action.yml
name: Should I deploy today? Github action
author: Tim Elfrink  
description: Every time you try to deploy we check at shouldideploy.today if this is a good idea.
inputs:
  timezone: 
    description: 'Timezone'
    required: True
    default: 'UTC'
outputs:
  time: # id of output
    description: 'Should we deploy?'
runs:
  using: 'composite'
  steps:
    - run: python ${{ github.action_path }}/main.py ${{ inputs.timezone }} ${{ github.event.head_commit.message }}
      shell: bash